services:
  - type: web
    name: ml-monitor-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: ML Monitor API
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true # Render auto-generates this
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: DATABASE_URL
        value: sqlite:///./data/ml_monitor.db
